#!/bin/bash

echo "🔧 GitHub API Setup Guide"
echo "========================="
echo ""
echo "To fetch real data from GitHub, you need a Personal Access Token."
echo ""
echo "1. Go to: https://github.com/settings/tokens"
echo "2. Click 'Generate new token' -> 'Generate new token (classic)'"
echo "3. Give it a name like: 'Portfolio Website'"
echo "4. Select these scopes:"
echo "   ✅ repo (Full control of private repositories)"
echo "   ✅ user (Update ALL user data)"
echo "   ✅ read:user (Read ALL user profile data)"
echo ""
echo "5. Copy the generated token"
echo "6. Replace 'your_github_personal_access_token_here' in .env.local with your token"
echo ""
echo "⚠️  IMPORTANT: Keep your token secret! Don't commit it to git."
echo ""
echo "Current .env.local file:"
cat .env.local 2>/dev/null || echo "File not found"
